version: 2.1
orbs:
  k8s: circleci/kubernetes@0.7.0
  slack: circleci/slack@3.4.2
commands:
  npm_install:
    description: "Install npm modules"
    steps:
      - restore_cache:
          name: Restore npm cache
          keys:
            - npm-v1-{{ checksum "package-lock.json" }}
            - npm-v1-
      - run:
          name: Install npm modules
          command: npm ci
      - save_cache:
          name: Save NPM cache
          key: npm-v1-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
  build:
    description: "Build"
    steps:
      - run:
          name: "Compile project"
          command: npm run build
  versioning:
    description: "Add version to build"
    parameters:
      target_branch:
        type: string
    steps:
      - run:
          name: Tag build
          command: echo "<< parameters.target_branch >> $(date -u +'%Y-%m-%dT%H:%M:%SZ')" > dist/compressed/version
  docker_build_push:
    description: "Build and Push image to docker hub"
    parameters:
      docker_image_latest_tag:
        type: string
        default: "latest-staging"
      docker_image_tag:
        type: string
        default: ${CIRCLE_SHA1}
    steps:
      - setup_remote_docker
      - run:
          name: Building docker image
          command: |
            docker build -t ${DOCKHUB_ORGANISATION}/binary-static-webtrader:<< parameters.docker_image_tag >> -t ${DOCKHUB_ORGANISATION}/binary-static-webtrader:<< parameters.docker_image_latest_tag >> .
      - run:
          name: Pushing Image to docker hub
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push ${DOCKHUB_ORGANISATION}/binary-static-webtrader
  k8s_deploy:
    description: "Deploy to k8s cluster"
    parameters:
      k8s_version:
        type: string
        default: ${CIRCLE_SHA1}
      k8s_namespace:
        type: string
        default: "webtrader-binary-com-staging"
    steps:
      - k8s/install-kubectl
      - run:
          name: Deploying to k8s cluster for service << parameters.k8s_namespace >>
          command: |
            export NAMESPACE=<< parameters.k8s_namespace >>
            git clone https://github.com/binary-com/devops-ci-scripts
            cd devops-ci-scripts/k8s-build_tools
            echo $CA_CRT | base64 --decode > ca.crt
            ./release.sh binary-static-webtrader << parameters.k8s_version >>
  notify_slack:
    description: "Notify slack"
    steps:
      - slack/status:
          include_project_field: false
          failure_message: "Release failed for webtrader with version *$(cat dist/compressed/version)*"
          success_message: "Release succeeded for webtrader with version *$(cat dist/compressed/version)*"
          webhook: ${SLACK_WEBHOOK}

  publish_to_pages_staging:
    description: "Publish to cloudflare pages"
    steps:
      - run:
          name: "Publish to cloudflare pages (staging)"
          command: |
            cd dist/compressed
            npx wrangler pages publish . --project-name=webtrader-pages --branch=staging
            echo "New staging website - http://staging.cf-pages-webtrader.binary.com"

  publish_to_pages_production:
    description: "Publish to cloudflare pages"
    steps:
      - run:
          name: "Publish to cloudflare pages (production)"
          command: |
            cd dist/compressed
            npx wrangler pages publish . --project-name=webtrader-pages --branch=main
            echo "New website - http://cf-pages-webtrader.binary.com"

jobs:
  build:
    docker:
      - image: circleci/node:12.13.0-stretch
    steps:
      - checkout
      - npm_install
      - build
  release_staging:
    docker:
      - image: circleci/node:12.13.0-stretch
    steps:
      - checkout
      - npm_install
      - build
      - versioning:
          target_branch: "staging"
      - persist_to_workspace:
          root: dist
          paths:
            - .
      - docker_build_push
      - k8s_deploy
      - notify_slack
  release_production:
    docker:
      - image: circleci/node:12.13.0-stretch
    steps:
      - checkout
      - npm_install
      - build
      - versioning:
          target_branch: "production"
      - persist_to_workspace:
          root: dist
          paths:
            - .
      - docker_build_push:
          docker_image_latest_tag: "latest"
          docker_image_tag: ${CIRCLE_TAG}
      - k8s_deploy:
          k8s_namespace: "webtrader-binary-com-production"
          k8s_version: ${CIRCLE_TAG}
      - notify_slack
 
  publish_cloudflare_staging:
    docker:
      - image: circleci/node:16.13.1-stretch
    steps:
      - attach_workspace:
          at: dist
      - publish_to_pages_staging

  publish_cloudflare_production:
    docker:
      - image: circleci/node:16.13.1-stretch
    steps:
      - attach_workspace:
          at: dist
      - publish_to_pages_production

workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore: /^master$/
  release:
    jobs:
      - release_staging:
          filters:
            branches:
              only: /^master$/
          context: binary-frontend-artifact-upload
      - publish_cloudflare_staging:
          requires:
            - release_staging
          filters:
            branches:
              only: /^master$/
          context: binary-frontend-artifact-upload
      - release_production:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^production.*/
          context: binary-frontend-artifact-upload
      - publish_cloudflare_production:
          requires:
            - release_production
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^production.*/
          context: binary-frontend-artifact-upload
